#!/bin/sh

###Walpaper Setter ###
feh --bg-scale --no-fehbg --randomize --recursive /home/nemi//Downloads/wallpapers &

##Fonts and Style ###
xrdb ~/.config/x11/xresources &


### Compton###
#xcompmgr &

### Browser History ###
rm -rf .surf/ .cache/ .mozilla/ .config/BraveSoftware/ &

### Crusor icon ###
xsetroot -cursor_name left_ptr &

### Language ###
setxkbmap us,np -option grp:ctrl_shift_toggle &

### volume all max ###
## Headphone ##
amixer set Headphone 100% &
##Speaker##
amixer set Front 100% &

### Launch xmonad ###
exec dbus-launch xmonad

