#!/bin/sh

### Use same file for xinit & xsession ###
##Fonts and Style ###
xrdb-merge /home/nemi/.config/x11/xresources &

### Browser History ###
bleachbit -c firefox.* &

rm -rf /home/nemi/.config/BraveSoftware &

rm -rf /home/nemi/.cache &

#rm -rf /home/nemi/.config/google-chrome/

### Crusor icon ###
xsetroot -cursor_name left_ptr &

### IMP ###
source ~/.bash_profile &

source ~/.bashrc & 

source ~/.profile &

### Networks ###
nm-applet &

### Language Selection ###

### Authenticate Gparted ###
lxpolkit &

### Clipboard ###
clipmenud &

### Notification ### 
dunst &

### Screensaver ###
xscreensaver --no-splash &

### transparency ###
picom &

### Mounting ###
udiskie -Ant &

### volume all max ###
# Headphone 
amixer -c 0 set Headphone 100% &

#Speaker
amixer -c 0 set Front 100% &

### Launch xmonad ###
exec xmonad

