#Aliases

# some more ls aliases
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'

#my
alias sx="startx"
alias xx="xrdb ~/.config/x11/xresources"
alias sbrc="source ~/.config/bash/bashrc"
alias vbrc="vim ~/.config/bash/bashrc"
alias vxr="vim ~/.config/x11/xresources"
alias ls="ls --color=auto"
alias lh="ls -lah --color=auto"
alias la="ls -a --color=auto"
alias animdl="python3 ~/animdl/runner.py"
alias vxhs="vi ~/.config/xmonad/xmonad.hs"
alias vxrc="vi ~/.config/x11/xinitrc"
alias bcc="rm -rf .cache/ .config/BraveSoftware/ .mozilla/ .cache/mozilla/ ~/.surf"
alias reboot="sudo reboot -r now"
alias halt="sudo halt -r now"
alias install="sudo apt install"
alias remove="sudo apt remove"
alias rmbh="rm -rf ~/.bash_history*"
alias vba="vi /home/nemi/.config/bash/bash_aliases"
#Git Alias
alias config="/usr/bin/git --git-dir=$HOME/.cfg --work-tree=$HOME"

#Python alias##
alias python="python3.11"
alias python3="python3.11"

#change_wallapper
alias wl="feh --bg-scale --no-fehbg --randomize --recursive /home/nemi//Downloads/wallpapers "


