source ~/.bashrc

# Created by `pipx` on 2023-09-18 07:09:19
export PATH="/home/nemi/.local/bin:/usr/sbin:$PATH"

#SET_XDG_RUNTIME_DIR
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi


